[
    {
      _id: '10',
      type: 'credit',
      amount: 7000,
      purpose: 'Advance payment from client',
      account: { name: 'Client Payment' },
      vendor: { name: 'ABC Traders' },
      files: ['receipt1.pdf'],
      createdAt: '2025-04-08T10:00:00Z',
    },
    {
      _id: '20',
      type: 'debit',
      amount: 1200,
      purpose: 'Labour charges',
      account: { name: 'Labour Expenses' },
      vendor: { name: 'XYZ Workers' },
      files: [],
      createdAt: '2025-04-07T14:30:00Z',
    },
    {
      _id: '30',
      type: 'debit',
      amount: 300,
      purpose: 'Stationery purchase',
      account: { name: 'Office Supplies' },
      vendor: { name: 'Stationery Hub' },
      files: ['invoice.pdf'],
      createdAt: '2025-04-06T09:15:00Z',
    },
    {
      _id: '1',
      type: 'credit',
      amount: 5000,
      purpose: 'Advance payment from client',
      account: { name: 'Client Payment' },
      vendor: { name: 'ABC Traders' },
      files: ['receipt1.pdf'],
      createdAt: '2025-04-08T10:00:00Z',
    },
    {
      _id: '2',
      type: 'debit',
      amount: 1200,
      purpose: 'Labour charges',
      account: { name: 'Labour Expenses' },
      vendor: { name: 'XYZ Workers' },
      files: [],
      createdAt: '2025-04-07T14:30:00Z',
    },
    {
      _id: '3',
      type: 'debit',
      amount: 300,
      purpose: 'Stationery purchase',
      account: { name: 'Office Supplies' },
      vendor: { name: 'Stationery Hub' },
      files: ['invoice.pdf'],
      createdAt: '2025-04-06T09:15:00Z',
    },
    {
      _id: '4',
      type: 'credit',
      amount: 2500,
      purpose: 'Service payment received',
      account: { name: 'Service Income' },
      vendor: { name: 'Client A' },
      files: [],
      createdAt: '2025-04-05T11:45:00Z',
    },
    {
      _id: '9',
      type: 'debit',
      amount: 1200,
      purpose: 'Labour charges',
      account: { name: 'Labour Expenses' },
      vendor: { name: 'XYZ Workers' },
      files: [],
      createdAt: '2025-03-07T14:30:00Z',
    },
    {
      _id: '10',
      type: 'debit',
      amount: 300,
      purpose: 'Stationery purchase',
      account: { name: 'Office Supplies' },
      vendor: { name: 'Stationery Hub' },
      files: ['invoice.pdf'],
      createdAt: '2025-03-06T09:15:00Z',
    },
    {
      _id: '10',
      type: 'credit',
      amount: 2500,
      purpose: 'Service payment received',
      account: { name: 'Service Income' },
      vendor: { name: 'Client A' },
      files: [],
      createdAt: '2024-04-05T11:45:00Z',
    }
  ]